### ISSUE TITLE
Fix and separate dockerfile

### ISSUE THREAD

**Issue by KINGTUT10101** [KINGTUT10101/ContentSharingPlatform#4]
Right now, the dockerfile builds the frontend content and starts the backend. We should separate the project so each major part runs in a different container to provide better scalability. Plus, the changes to the backend filestructure probably broke stuff anyway

**Comment by Amnish04** [comment]
@KINGTUT10101 
Hi, could you give me more details on this. I would like to contribute.

From what I understand, I need to create a `Dockerfile` for both frontend and backend.

And then, create a `docker-compose.yml` to spin up containers for both services.

**Comment by KINGTUT10101** [comment]
Hi! I really appreciate the offer! However, I can't accept your help with stuff on this repo yet, since I will be submitting it for a school project. I have the repo set to public right now so the professor and my group members can more easily view it. If you'd like to help in the future, just wait until after December 20th. The project should be fully graded after that.

Thanks again!

**Comment by Amnish04** [comment]
I see, no worries. Thanks for clarifying!

**Comment by KINGTUT10101** [comment]
https://github.com/KINGTUT10101/ContentSharingPlatform/commit/b33cd4f841dff68eff42974cb5beae2b50ee7544

The repo now has a docker-compose file and everything is properly separated. The databases don't have data though, so the backend won't load currently, but that's okay for now
